manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: daskygit
      url-base: https://github.com/daskygit
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-ps2-dasky-final   # <--- New unique name
      remote: daskygit
      repo-path: zmk-ps2-driver   # <--- Correct Repo Name on GitHub
      path: drivers/dasky-final   # <--- New clean folder
      revision: main
  self:
    path: config
