manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: daskygit
      url-base: https://github.com/daskygit
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-ps2-dasky          # Unique name to force fresh setup
      remote: daskygit
      repo-path: zmk-ps2-driver    # The actual repo on GitHub
      path: modules/dasky-ps2      # Downloads to this brand new folder
      revision: main
  self:
    path: config
