manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.5-branch
      import: app/west.yml
    - name: ps2-driver-kim
      url: https://github.com/infused-kim/kb_zmk_ps2_mouse_trackpoint_driver
      path: modules/ps2-kim
      revision: main
  self:
    path: config
