manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: infused-kim
      url-base: https://github.com/infused-kim

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: trackpoint-rescue
      remote: infused-kim
      repo-path: kb_zmk_ps2_mouse_trackpoint_driver
      revision: main
      path: driver-rescue

  self:
    path: config
