manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: daskygit
      url-base: https://github.com/daskygit
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: trackpoint-driver  # <--- CHANGED NAME TO FORCE CLEAN DOWNLOAD
      remote: daskygit
      repo-path: kb_zmk_ps2_mouse_trackpoint_driver
      revision: main
  self:
    path: config
