manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: daskygit
      url-base: https://github.com/daskygit
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: dasky-driver-final   # <--- New Unique Name
      remote: daskygit
      repo-path: zmk-ps2-driver
      path: modules/dasky-final  # <--- New Clean Folder
      revision: main
  self:
    path: config
