manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: filippor
      url-base: https://github.com/filippor
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-ps2-driver
      remote: filippor
      repo-path: kb_zmk_ps2_mouse_trackpoint_driver
      revision: fix/zephyr-4.1
  self:
    path: config
