manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-ps2-driver
      remote: infused-kim
      repo-path: kb_zmk_ps2_mouse_trackpoint_driver
      revision: main
  self:
    path: config
